version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: cipherlock
    main: .
    ldflags:
      - -s -w -X github.com/valonmulolli/cipherlock/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - SECURITY.md
      - cipherlock.1

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
