package cmd

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var keyCmd = &cobra.Command{
	Use:   "key [command]",
	Short: "Manage encryption keys",
	Long:  `Commands for managing and inspecting X25519 encryption keys.`,
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
}

var keyFingerprintCmd = &cobra.Command{
	Use:   "fingerprint <pubkey-file>",
	Short: "Display the SHA-256 fingerprint of a public key",
	Long: `Display the SHA-256 fingerprint of a public key file for
out-of-band verification.

The fingerprint is a SHA-256 hash of the raw X25519 public key bytes.
Two parties can compare fingerprints over a separate communication
channel (e.g. a phone call) to confirm they share the same key.

Supports .pub files generated by 'cipherlock dial'.
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		data, err := os.ReadFile(args[0])
		if err != nil {
			return fmt.Errorf("reading public key: %w", err)
		}

		raw := strings.TrimSpace(string(data))
		pubBytes, err := base64.StdEncoding.DecodeString(raw)
		if err != nil {
			return fmt.Errorf("decoding public key (expected base64): %w", err)
		}

		if len(pubBytes) != 32 {
			return fmt.Errorf("invalid public key length: got %d bytes, expected 32", len(pubBytes))
		}

		hash := sha256.Sum256(pubBytes)

		// Format as groups of 4 hex chars (2 bytes per group), uppercase
		var parts []string
		for i := 0; i < len(hash); i += 2 {
			parts = append(parts, fmt.Sprintf("%02X%02X", hash[i], hash[i+1]))
		}

		fmt.Println(strings.Join(parts, " "))
		return nil
	},
}

func init() {
	keyCmd.AddCommand(keyFingerprintCmd)
	rootCmd.AddCommand(keyCmd)
}
